export function getGlucoseLevel(value: number): {
  label: string;
  range: string;
  className: string;
  textClass: string;
  bgClass: string;
} {
  if (value < 54) return {
    label: 'Critical Low',
    range: 'Below 54',
    className: 'bg-red-900 text-white',
    textClass: 'text-glucose-critical-low',
    bgClass: 'bg-glucose-critical-low',
  };
  if (value < 70) return {
    label: 'Low',
    range: '54–69',
    className: 'bg-orange-500 text-white',
    textClass: 'text-glucose-low',
    bgClass: 'bg-glucose-low',
  };
  if (value <= 180) return {
    label: 'In Range',
    range: '70–180',
    className: 'bg-green-500 text-white',
    textClass: 'text-glucose-in-range',
    bgClass: 'bg-glucose-in-range',
  };
  if (value <= 250) return {
    label: 'High',
    range: '181–250',
    className: 'bg-yellow-500 text-white',
    textClass: 'text-glucose-high',
    bgClass: 'bg-glucose-high',
  };
  return {
    label: 'Critical High',
    range: 'Above 250',
    className: 'bg-red-600 text-white',
    textClass: 'text-glucose-critical-high',
    bgClass: 'bg-glucose-critical-high',
  };
}

export function getGMILevel(gmi: number): { label: string; color: string; textColor: string } {
  if (gmi < 5.7) return { label: 'Excellent', color: 'text-green-600', textColor: 'text-green-600' };
  if (gmi < 6.5) return { label: 'Good (Pre-diabetes range)', color: 'text-green-500', textColor: 'text-green-500' };
  if (gmi < 7.0) return { label: 'Good Control', color: 'text-primary-600', textColor: 'text-primary-600' };
  if (gmi < 8.0) return { label: 'Fair — Needs Improvement', color: 'text-yellow-600', textColor: 'text-yellow-600' };
  return { label: 'Poor — Needs Action', color: 'text-red-600', textColor: 'text-red-600' };
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
  });
}

export function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-US', {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

export function formatTime(dateStr: string): string {
  return new Date(dateStr).toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });
}

export function mealContextLabel(ctx: string): string {
  const labels: Record<string, string> = {
    fasting: 'Fasting',
    before_meal: 'Before Meal',
    after_meal: 'After Meal',
    bedtime: 'Bedtime',
    overnight: 'Overnight',
    other: 'Other',
  };
  return labels[ctx] || ctx;
}

export function sourceLabel(src: string): string {
  const labels: Record<string, string> = {
    manual: 'Manual',
    meter: 'Meter',
    CGM: 'CGM',
  };
  return labels[src] || src;
}

export function diabetesTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    Type1: 'Type 1',
    Type2: 'Type 2',
    Gestational: 'Gestational',
    'Pre-diabetic': 'Pre-diabetic',
    Other: 'Other',
  };
  return labels[type] || type;
}

export function getGlucoseRangeClass(value: number): string {
  if (value < 54) return 'glucose-critical-low';
  if (value < 70) return 'glucose-low';
  if (value <= 180) return 'glucose-in-range';
  if (value <= 250) return 'glucose-high';
  return 'glucose-critical-high';
}

export function exportToPdf(content: string, filename: string = 'report.pdf') {
  // Print-friendly approach: open a new window with printable content
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>BGMIQ Report</title>
      <style>
        body { font-family: 'Inter', Arial, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
        h1 { color: #2E7D32; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
        h2 { color: #388E3C; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        th { background: #f5f5f5; }
        .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 15px 0; }
        .kpi-card { border: 1px solid #e0e0e0; border-radius: 8px; padding: 15px; text-align: center; }
        .kpi-value { font-size: 24px; font-weight: bold; color: #2E7D32; }
        .kpi-label { font-size: 12px; color: #666; }
        .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">Generated by BGMIQ - Diabetes Glucose Monitor | ${new Date().toLocaleDateString()}</div>
      <script>
        window.onload = function() { window.print(); };
      <\/script>
    </body>
    </html>
  `);
  win.document.close();
}